# This workflow publishes the module to Luarocks and is triggered when a Draft release is published.

name: Publish Release

on:
  release:
    types: [published]

jobs:
  upload_to_luarocks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.COMMIT_ACCESS_TOKEN }}

    - name: Bump Rockspec version
      run: .ci/scripts/bump-rockspec.sh ${{ github.event.release.tag_name }}

    - name: Install dependencies
      run: .ci/scripts/install-deps.sh

    - name: Upload to Luarocks
      run: .ci/scripts/upload.sh ${{ secrets.LUAROCKS_KEY }}
