# This workflow publishes the module to Luarocks and is triggered when a Draft release is published.

name: Publish Release

on:
  release:
    types: [released]

jobs:
  upload_to_luarocks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Bump Rockspec version
      run: .ci/scripts/bump-rockspec.sh ${{ github.event.release.tag_name }} ${{ secrets.COMMIT_ACCESS_TOKEN }} ${{ github.repository }} ${{ github.event.release.target_commitish }}

    - name: Install dependencies
      run: .ci/scripts/install-deps.sh

    - name: Upload to Luarocks
      run: .ci/scripts/upload.sh ${{ secrets.LUAROCKS_KEY }}
